"use client";

import Link from "next/link";
import { useEffect, useState, type FormEvent } from "react";
import { KeyRound, Loader2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function RedefinirSenhaPage() {
  const [recoveryAllowed, setRecoveryAllowed] = useState(false); const [checking, setChecking] = useState(true);
  const [completed, setCompleted] = useState(false);
  const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState<{ tone: "success" | "error"; text: string } | null>(null);
  useEffect(() => { const supabase = createClient(); if (!supabase) { setChecking(false); return; } const { data: listener } = supabase.auth.onAuthStateChange((event) => { if (event === "PASSWORD_RECOVERY") setRecoveryAllowed(true); setChecking(false); }); const timeout = window.setTimeout(() => setChecking(false), 1500); return () => { window.clearTimeout(timeout); listener.subscription.unsubscribe(); }; }, []);
  async function reset(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(null); if (!recoveryAllowed) return setMessage({ tone: "error", text: "Link de recuperação inválido ou expirado." }); if (!password || !confirmation) return setMessage({ tone: "error", text: "Preencha todos os campos de senha." }); if (password.length < 8) return setMessage({ tone: "error", text: "A nova senha deve ter pelo menos 8 caracteres." }); if (password !== confirmation) return setMessage({ tone: "error", text: "As senhas não coincidem." }); const supabase = createClient(); if (!supabase) return; setLoading(true); const { error } = await supabase.auth.updateUser({ password }); setLoading(false); if (error) return setMessage({ tone: "error", text: "Não foi possível redefinir a senha. Solicite um novo link." }); setPassword(""); setConfirmation(""); setRecoveryAllowed(false); setCompleted(true); setMessage({ tone: "success", text: "Senha redefinida com sucesso. Você já pode entrar." }); await supabase.auth.signOut(); }
  return <main className="grid min-h-screen place-items-center bg-[#f4f7f7] p-6"><section className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><span className="grid size-12 place-items-center rounded-xl bg-teal-50 text-teal-700"><KeyRound/></span><h1 className="mt-5 text-2xl font-bold text-slate-900">Criar nova senha</h1><p className="mt-2 text-sm text-slate-500">Use o link enviado para seu e-mail para autorizar a redefinição.</p>{checking?<p className="mt-6 flex items-center gap-2 text-sm text-slate-500"><Loader2 className="size-4 animate-spin"/>Validando link...</p>:completed?<div className="mt-6"><p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message?.text}</p><Link href="/login" className="mt-4 inline-block text-sm font-semibold text-teal-700">Ir para o login</Link></div>:recoveryAllowed?<form onSubmit={reset} className="mt-6 space-y-4"><label className="block text-sm font-semibold text-slate-700">Nova senha<input type="password" required minLength={8} autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 outline-none focus:border-teal-500"/></label><label className="block text-sm font-semibold text-slate-700">Confirmar nova senha<input type="password" required minLength={8} autoComplete="new-password" value={confirmation} onChange={event=>setConfirmation(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 outline-none focus:border-teal-500"/></label>{message&&<p role="status" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{message.text}</p>}<button disabled={loading} className="flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-teal-600 font-semibold text-white disabled:opacity-60">{loading&&<Loader2 className="size-4 animate-spin"/>}Redefinir senha</button></form>:<div className="mt-6"><p role="alert" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Link de recuperação inválido ou expirado. Solicite um novo link.</p><Link href="/login" className="mt-4 inline-block text-sm font-semibold text-teal-700">Voltar ao login</Link></div>}</section></main>;
}
