"use client";
import {useCallback,useEffect,useState,type FormEvent,type ReactNode} from "react";
import {ArrowLeft,CheckCircle2,KeyRound,Loader2,Pencil,Plus,ShieldCheck,UserCheck,UserX,X} from "lucide-react";
import Link from "next/link";
import {actionLabels,permissionGroups,rolePresets,type BaseRole} from "@/lib/permissions";

type Override={permission_key:string;allowed:boolean};
type UserRow={id:string;email:string;full_name:string;role:BaseRole;phone:string|null;whatsapp:string|null;whatsapp_enabled:boolean;active:boolean;last_login_at:string|null;created_at:string;permissions:Override[]};
type Form={fullName:string;email:string;password:string;confirmPassword:string;phone:string;whatsapp:string;role:BaseRole;active:boolean;whatsappEnabled:boolean;permissions:string[]};
const blank:Form={fullName:"",email:"",password:"",confirmPassword:"",phone:"",whatsapp:"5581983857466",role:"vendedor",active:true,whatsappEnabled:true,permissions:rolePresets.vendedor};
const roleLabel:Record<BaseRole,string>={admin:"Administrador",vendedor:"Vendedor",tecnico:"Técnico"};
type ApiBody={error?:string;diagnostics?:{supabaseUrlConfigured:boolean;serviceRoleConfigured:boolean};attendants?:UserRow[]};
const effective=(row:UserRow)=>{const set=new Set(rolePresets[row.role]);for(const item of row.permissions??[]){if(item.allowed)set.add(item.permission_key);else set.delete(item.permission_key)}return [...set]};
const date=(value:string|null)=>value?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"Nunca";
const apiError=(body:ApiBody,fallback:string)=>`${body.error??fallback}${body.diagnostics?` SUPABASE_URL: ${body.diagnostics.supabaseUrlConfigured}. SERVICE_ROLE: ${body.diagnostics.serviceRoleConfigured}.`:""}`;

export function AttendantManagement(){
 const[items,setItems]=useState<UserRow[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const[editing,setEditing]=useState<UserRow|null>(null),[creating,setCreating]=useState(false),[resetting,setResetting]=useState<UserRow|null>(null),[summary,setSummary]=useState<UserRow|null>(null),[form,setForm]=useState<Form>(blank);
 const load=useCallback(async()=>{setLoading(true);const response=await fetch("/api/admin/attendants",{cache:"no-store"});const body=await response.json() as ApiBody;if(response.ok)setItems(body.attendants??[]);else setError(apiError(body,"Não foi possível carregar os usuários."));setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 const openCreate=()=>{setForm({...blank,permissions:[...rolePresets.vendedor]});setCreating(true);setError("")};
 const openEdit=(item:UserRow)=>{setEditing(item);setForm({fullName:item.full_name,email:item.email,password:"",confirmPassword:"",phone:item.phone??"",whatsapp:item.whatsapp??"",role:item.role,active:item.active,whatsappEnabled:item.whatsapp_enabled,permissions:effective(item)});setError("")};
 const setRole=(role:BaseRole)=>setForm({...form,role,permissions:[...rolePresets[role]]});
 const togglePermission=(key:string)=>setForm({...form,permissions:form.permissions.includes(key)?form.permissions.filter(x=>x!==key):[...form.permissions,key]});
 async function save(event:FormEvent){event.preventDefault();if(!editing&&(form.password.length<8||form.password!==form.confirmPassword))return setError(form.password.length<8?"A senha inicial deve ter pelo menos 8 caracteres.":"As senhas não coincidem.");setSaving(true);const response=await fetch(editing?`/api/admin/attendants/${editing.id}`:"/api/admin/attendants",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json() as ApiBody;setSaving(false);if(!response.ok)return setError(apiError(body,"Não foi possível salvar."));setCreating(false);setEditing(null);setSuccess("Usuário salvo com sucesso.");await load()}
 async function toggle(item:UserRow){const response=await fetch(`/api/admin/attendants/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({fullName:item.full_name,email:item.email,phone:item.phone??"",whatsapp:item.whatsapp??"",role:item.role,active:!item.active,whatsappEnabled:item.whatsapp_enabled,permissions:effective(item)})});const body=await response.json();if(!response.ok)return setError(body.error??"Não foi possível alterar o status.");setSuccess(item.active?"Usuário desativado.":"Usuário reativado.");await load()}
 async function resetPassword(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!resetting)return;const data=new FormData(event.currentTarget);setSaving(true);const response=await fetch(`/api/admin/attendants/${resetting.id}/reset-password`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:data.get("password"),confirmPassword:data.get("confirmPassword")})});const body=await response.json();setSaving(false);if(!response.ok)return setError(body.error??"Não foi possível redefinir a senha.");setResetting(null);setSuccess("Senha redefinida com sucesso.")}
 return <div className="min-h-screen bg-[#f4f7f7] p-4 lg:p-8"><div className="mx-auto max-w-7xl"><Link href="/dashboard" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-teal-700"><ArrowLeft className="size-4"/>Voltar ao sistema</Link><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-bold">Gerenciar usuários</h1><p className="text-sm text-slate-500">Perfis base e permissões individuais de acesso.</p></div><button onClick={openCreate} className="btn"><Plus className="size-4"/>Novo usuário</button></header>
 {success&&<p className="mt-5 flex gap-2 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 className="size-5"/>{success}</p>}{error&&!creating&&!editing&&!resetting&&<p className="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
 <div className="mt-5 overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<div className="flex justify-center gap-2 p-12"><Loader2 className="animate-spin"/>Carregando usuários...</div>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50"><tr>{["Nome","E-mail","Perfil","Status","Último acesso","Ações"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t"><td className="px-4 py-4 font-semibold">{item.full_name}</td><td className="px-4 py-4">{item.email}</td><td className="px-4 py-4">{roleLabel[item.role]}</td><td className="px-4 py-4">{item.active?"Ativo":"Inativo"}</td><td className="px-4 py-4">{date(item.last_login_at)}</td><td className="px-4 py-4"><div className="flex gap-3"><button title="Editar" onClick={()=>openEdit(item)}><Pencil className="size-4"/></button><button title="Permissões" onClick={()=>setSummary(item)}><ShieldCheck className="size-4"/></button><button title="Resetar senha" onClick={()=>setResetting(item)}><KeyRound className="size-4"/></button><button title={item.active?"Desativar":"Ativar"} onClick={()=>void toggle(item)}>{item.active?<UserX className="size-4"/>:<UserCheck className="size-4"/>}</button></div></td></tr>)}</tbody></table></div>}</div></div>
 {(creating||editing)&&<Modal title={editing?"Editar usuário":"Novo usuário"} close={()=>{setCreating(false);setEditing(null)}}><form onSubmit={save}><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome" value={form.fullName} set={v=>setForm({...form,fullName:v})}/><Field label="E-mail" type="email" value={form.email} set={v=>setForm({...form,email:v})}/>{!editing&&<><Field label="Senha inicial" type="password" value={form.password} set={v=>setForm({...form,password:v})}/><Field label="Confirmar senha" type="password" value={form.confirmPassword} set={v=>setForm({...form,confirmPassword:v})}/></>}<Field label="Telefone" value={form.phone} set={v=>setForm({...form,phone:v})}/><Field label="WhatsApp" value={form.whatsapp} set={v=>setForm({...form,whatsapp:v})}/><label className="field">Perfil<select className="input" value={form.role} onChange={e=>setRole(e.target.value as BaseRole)}><option value="admin">Administrador</option><option value="vendedor">Vendedor</option><option value="tecnico">Técnico</option></select></label><label className="flex items-center gap-2 pt-6"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Ativo</label></div><PermissionEditor role={form.role} selected={form.permissions} toggle={togglePermission}/>{error&&<p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm">{error}</p>}<Actions saving={saving}/></form></Modal>}
 {resetting&&<Modal title={`Resetar senha — ${resetting.full_name}`} close={()=>setResetting(null)}><form onSubmit={resetPassword}><div className="grid gap-4 sm:grid-cols-2"><label className="field">Nova senha<input className="input" name="password" type="password" minLength={8} required/></label><label className="field">Confirmar senha<input className="input" name="confirmPassword" type="password" minLength={8} required/></label></div><Actions saving={saving}/></form></Modal>}
 {summary&&<Modal title={`Permissões — ${summary.full_name}`} close={()=>setSummary(null)}><p className="mb-4"><b>PERFIL:</b> {roleLabel[summary.role]}</p><div className="grid gap-2 sm:grid-cols-2">{permissionGroups.flatMap(g=>g.modules).map(module=><p key={module.key}>{effective(summary).some(p=>p===`${module.key}.view`)?"✓":"✕"} {module.label}</p>)}</div></Modal>}
 </div>}

function PermissionEditor({role,selected,toggle}:{role:BaseRole;selected:string[];toggle:(key:string)=>void}){if(role==="admin")return <div className="mt-5 rounded-xl bg-teal-50 p-4 font-semibold text-teal-900">Acesso administrativo completo</div>;return <section className="mt-6"><h3 className="font-bold">Permissões de acesso</h3><div className="mt-3 grid gap-4 md:grid-cols-2">{permissionGroups.map(group=><fieldset key={group.label} className="rounded-xl border p-4"><legend className="px-2 text-xs font-bold text-slate-500">{group.label}</legend>{group.modules.map(module=><div key={module.key} className="mb-3"><b className="text-sm">{module.label}</b><div className="mt-1 flex flex-wrap gap-3">{module.actions.map(action=>{const key=`${module.key}.${action}`;return <label key={key} className="text-xs"><input className="mr-1" type="checkbox" checked={selected.includes(key)} onChange={()=>toggle(key)}/>{actionLabels[action]??action}</label>})}</div></div>)}</fieldset>)}</div></section>}
function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="field">{label}<input required={label==="Nome"||label==="E-mail"} className="input" type={type} value={value} onChange={e=>set(e.target.value)}/></label>}
function Actions({saving}:{saving:boolean}){return <div className="mt-5 flex justify-end"><button disabled={saving} className="btn">{saving&&<Loader2 className="size-4 animate-spin"/>}{saving?"Salvando...":"Salvar"}</button></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="max-h-[94vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-6"><div className="mb-5 flex justify-between"><h2 className="font-bold">{title}</h2><button aria-label="Fechar" onClick={close}><X/></button></div>{children}</div></div>}
