"use client";

import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react";
import { ArrowLeft, CheckCircle2, KeyRound, Loader2, Pencil, Plus, ShieldCheck, UserCheck, UserX, X } from "lucide-react";
import Link from "next/link";

type Role = "admin" | "attendant" | "technician";
type Attendant = { id:string; email:string; full_name:string; role:Role; phone:string|null; whatsapp:string|null; whatsapp_enabled:boolean; active:boolean; last_login_at:string|null; created_at:string };
type Form = { fullName:string; email:string; password:string; confirmPassword:string; phone:string; whatsapp:string; role:Role; active:boolean; whatsappEnabled:boolean };
const blank:Form={fullName:"",email:"",password:"",confirmPassword:"",phone:"",whatsapp:"5581983857466",role:"attendant",active:true,whatsappEnabled:true};
const roleLabel:Record<Role,string>={admin:"Administrador",attendant:"Atendente",technician:"Técnico"};
type ApiBody={error?:string;diagnostics?:{supabaseUrlConfigured:boolean;serviceRoleConfigured:boolean};attendants?:Attendant[]};

function formatPhone(value:string|null){if(!value)return "—";const n=value.replace(/\D/g,"");return n==="5581983857466"?"+55 (81) 98385-7466":value}
function date(value:string|null){return value?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"Nunca"}
function apiError(body:ApiBody,fallback:string){const status=body.diagnostics?` SUPABASE_URL configurada: ${body.diagnostics.supabaseUrlConfigured}. SERVICE_ROLE configurada: ${body.diagnostics.serviceRoleConfigured}.`:"";return `${body.error??fallback}${status}`}

export function AttendantManagement(){
 const [items,setItems]=useState<Attendant[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");
 const [editing,setEditing]=useState<Attendant|null>(null);const [creating,setCreating]=useState(false);const [resetting,setResetting]=useState<Attendant|null>(null);const [permissions,setPermissions]=useState<Attendant|null>(null);const [form,setForm]=useState<Form>(blank);
 const load=useCallback(async()=>{setLoading(true);setError("");const response=await fetch("/api/admin/attendants",{cache:"no-store"});const body=await response.json() as ApiBody;if(!response.ok)setError(apiError(body,"Não foi possível carregar os atendentes."));else setItems(body.attendants??[]);setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 function openCreate(){setForm(blank);setCreating(true);setError("");setSuccess("")}
 function openEdit(item:Attendant){setEditing(item);setForm({fullName:item.full_name,email:item.email,password:"",confirmPassword:"",phone:item.phone??"",whatsapp:item.whatsapp??"",role:item.role,active:item.active,whatsappEnabled:item.whatsapp_enabled});setError("");setSuccess("")}
 async function save(event:FormEvent){event.preventDefault();if(!editing&&(form.password.length<8||form.password!==form.confirmPassword)){setError(form.password.length<8?"A senha inicial deve ter pelo menos 8 caracteres.":"As senhas não coincidem.");return}setSaving(true);setError("");const response=await fetch(editing?`/api/admin/attendants/${editing.id}`:"/api/admin/attendants",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json() as ApiBody;setSaving(false);if(!response.ok)return setError(apiError(body,"Não foi possível salvar."));setCreating(false);setEditing(null);setSuccess(editing?"Atendente atualizado com sucesso.":"Atendente criado ou sincronizado com sucesso.");await load()}
 async function toggle(item:Attendant){setError("");const response=await fetch(`/api/admin/attendants/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({fullName:item.full_name,email:item.email,phone:item.phone??"",whatsapp:item.whatsapp??"",role:item.role,active:!item.active,whatsappEnabled:item.whatsapp_enabled})});const body=await response.json();if(!response.ok)return setError(body.error??"Não foi possível alterar o status.");setSuccess(item.active?"Usuário desativado.":"Usuário reativado.");await load()}
 async function resetPassword(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!resetting)return;const data=new FormData(event.currentTarget);setSaving(true);setError("");const response=await fetch(`/api/admin/attendants/${resetting.id}/reset-password`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:data.get("password"),confirmPassword:data.get("confirmPassword")})});const body=await response.json();setSaving(false);if(!response.ok)return setError(body.error??"Não foi possível redefinir a senha.");setResetting(null);setSuccess("Senha redefinida com sucesso.")}
 return <div className="min-h-screen bg-[#f4f7f7] p-4 lg:p-8"><div className="mx-auto max-w-7xl"><Link href="/dashboard" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-teal-700"><ArrowLeft className="size-4"/>Voltar ao sistema</Link><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-bold text-slate-900">Atendentes</h1><p className="text-sm text-slate-500">Gerencie acessos, funções e o canal de atendimento da CIASSTEC.</p></div><button onClick={openCreate} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-teal-600 px-4 text-sm font-semibold text-white"><Plus className="size-4"/>Novo atendente</button></div>
 {success&&<p className="mt-5 flex gap-2 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 className="size-5"/>{success}</p>}{error&&!creating&&!editing&&!resetting&&<p className="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
 <div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading?<div className="flex justify-center gap-2 p-12 text-slate-500"><Loader2 className="animate-spin"/>Carregando atendentes...</div>:<div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Nome","E-mail","Função","Telefone","WhatsApp","Status","Último acesso","Ações"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t border-slate-100"><td className="px-4 py-4 font-semibold">{item.full_name}</td><td className="px-4 py-4">{item.email}</td><td className="px-4 py-4">{roleLabel[item.role]}</td><td className="px-4 py-4">{formatPhone(item.phone)}</td><td className="px-4 py-4">{item.whatsapp_enabled?formatPhone(item.whatsapp):"Não vinculado"}</td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${item.active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{item.active?"Ativo":"Inativo"}</span></td><td className="px-4 py-4 text-slate-500">{date(item.last_login_at)}</td><td className="px-4 py-4"><div className="flex gap-2"><button title="Editar" onClick={()=>openEdit(item)} className="text-teal-700"><Pencil className="size-4"/></button><button title={item.active?"Desativar":"Ativar"} onClick={()=>void toggle(item)} className={item.active?"text-rose-600":"text-emerald-600"}>{item.active?<UserX className="size-4"/>:<UserCheck className="size-4"/>}</button><button title="Redefinir senha" onClick={()=>{setResetting(item);setError("")}} className="text-amber-600"><KeyRound className="size-4"/></button><button title="Ver permissões" onClick={()=>setPermissions(item)} className="text-violet-600"><ShieldCheck className="size-4"/></button></div></td></tr>)}</tbody></table></div>}</div></div>
 {(creating||editing)&&<Modal title={editing?"Editar atendente":"Novo atendente"} close={()=>{setCreating(false);setEditing(null);setError("")}}><form onSubmit={save}><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome completo" value={form.fullName} set={v=>setForm({...form,fullName:v})}/><Field label="E-mail" type="email" value={form.email} set={v=>setForm({...form,email:v})}/>{!editing&&<><Field label="Senha inicial" type="password" value={form.password} set={v=>setForm({...form,password:v})}/><Field label="Confirmar senha" type="password" value={form.confirmPassword} set={v=>setForm({...form,confirmPassword:v})}/></>}<Field label="Telefone" value={form.phone} set={v=>setForm({...form,phone:v})}/><Field label="WhatsApp" value={form.whatsapp} set={v=>setForm({...form,whatsapp:v})}/><label className="text-xs font-semibold text-slate-600">Função<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as Role})} className="mt-1 h-10 w-full rounded-xl border px-3 text-sm"><option value="admin">Administrador</option><option value="attendant">Atendente</option><option value="technician">Técnico</option></select></label><label className="flex items-center gap-2 pt-6 text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Usuário ativo</label></div><label className="mt-4 flex items-center gap-2 rounded-xl bg-teal-50 p-3 text-sm text-teal-900"><input type="checkbox" checked={form.whatsappEnabled} onChange={e=>setForm({...form,whatsappEnabled:e.target.checked,whatsapp:e.target.checked?"5581983857466":form.whatsapp})}/>Atender WhatsApp CIASSTEC — +55 (81) 98385-7466</label>{error&&<p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}<Actions saving={saving}/></form></Modal>}
 {resetting&&<Modal title={`Redefinir senha — ${resetting.full_name}`} close={()=>{setResetting(null);setError("")}}><form onSubmit={resetPassword}><p className="mb-4 text-sm text-slate-600">Defina uma nova senha com pelo menos 8 caracteres. A senha atual nunca é exibida.</p><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold">Nova senha<input name="password" type="password" minLength={8} required className="mt-1 h-10 w-full rounded-xl border px-3"/></label><label className="text-xs font-semibold">Confirmar senha<input name="confirmPassword" type="password" minLength={8} required className="mt-1 h-10 w-full rounded-xl border px-3"/></label></div>{error&&<p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}<Actions saving={saving}/></form></Modal>}
 {permissions&&<Modal title={`Permissões — ${permissions.full_name}`} close={()=>setPermissions(null)}><ul className="space-y-2 text-sm text-slate-700">{permissions.role==="admin"?<><li>✓ Criar e editar atendentes</li><li>✓ Alterar funções e status</li><li>✓ Redefinir senhas</li><li>✓ Acessar configurações administrativas</li></>:<><li>✓ Acessar módulos operacionais enquanto ativo</li><li>✕ Criar ou editar usuários</li><li>✕ Alterar funções ou status</li><li>✕ Acessar APIs administrativas e secrets</li></>}</ul></Modal>}
 </div>}

function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="text-xs font-semibold text-slate-600">{label}<input required={label==="Nome completo"||label==="E-mail"} type={type} value={value} onChange={e=>set(e.target.value)} className="mt-1 h-10 w-full rounded-xl border px-3 text-sm"/></label>}
function Actions({saving}:{saving:boolean}){return <div className="mt-5 flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{saving&&<Loader2 className="size-4 animate-spin"/>}{saving?"Salvando...":"Salvar"}</button></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="max-h-[94vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><div className="mb-5 flex justify-between"><h2 className="font-bold">{title}</h2><button aria-label="Fechar" onClick={close}><X className="size-5"/></button></div>{children}</div></div>}
