"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Bot,Loader2,MessageCircle,RefreshCw,Send} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import {generateLocalAiSuggestion,useLocalAiStatus,type ChatSource,type ConversationMessage} from "@/lib/local-ai";
import {localWhatsAppFetch} from "@/lib/local-whatsapp";
type Row={id:string;customer_id:string;channel:string;customers:{name:string;phone:string;whatsapp:string|null}|null};
type Msg={id:string;content:string;direction:"inbound"|"outbound";sent_at:string;status:string};
export function ConversationInbox(){
 const[rows,setRows]=useState<Row[]>([]),[messages,setMessages]=useState<Msg[]>([]),[selected,setSelected]=useState<string|null>(null),[draft,setDraft]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[sources,setSources]=useState<ChatSource[]>([]);const{state:aiState,refresh:refreshAi}=useLocalAiStatus();
 const load=useCallback(async()=>{const db=createClient();if(!db){setNotice("Supabase não configurado.");setLoading(false);return}const r=await db.from("conversations").select("id,customer_id,channel,customers(name,phone,whatsapp)").order("last_message_at",{ascending:false}).limit(50);if(r.error)setNotice(`Aplique supabase/whatsapp_web_local.sql: ${r.error.message}`);else{const data=(r.data??[])as unknown as Row[];setRows(data);setSelected(v=>v??data[0]?.id??null)}setLoading(false)},[]);
 const loadMessages=useCallback(async(id:string)=>{const db=createClient();if(!db)return;const r=await db.from("messages").select("id,content,direction,sent_at,status").eq("conversation_id",id).order("sent_at");if(!r.error)setMessages((r.data??[])as Msg[])},[]);
 useEffect(()=>{void load();const t=setInterval(()=>void load(),10000);return()=>clearInterval(t)},[load]);useEffect(()=>{if(!selected)return;void loadMessages(selected);const t=setInterval(()=>void loadMessages(selected),5000);return()=>clearInterval(t)},[selected,loadMessages]);
 const active=rows.find(r=>r.id===selected)??null,aiMessages=useMemo<ConversationMessage[]>(()=>messages.map(m=>({role:m.direction==="inbound"?"cliente":"atendente",text:m.content})),[messages]);
 async function generate(){if(!active)return;if(aiState!=="online"){setNotice("CIASSTEC IA Local não está disponível.");void refreshAi();return}setBusy(true);setSources([]);try{const r=await generateLocalAiSuggestion({customerName:active.customers?.name??"Cliente",messages:aiMessages});setDraft(r.answer);setSources(r.sources??[]);setNotice("Sugestão gerada. Revise antes de enviar.")}catch(e){setNotice(e instanceof Error?e.message:"Falha na IA.")}finally{setBusy(false)}}
 async function send(){if(!active||!draft.trim())return;setBusy(true);setNotice("");try{if(active.channel!=="whatsapp_web_local")throw new Error("Este canal continua reservado à integração oficial da Meta.");const r=await localWhatsAppFetch("/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversationId:active.id,message:draft.trim()})}),body=await r.json();if(!r.ok)throw new Error(body.error==="invalid_payload"?`Dados inválidos: ${body.missing?.join(", ")||"corpo da requisição"}.`:body.error??`Falha no conector local (HTTP ${r.status}).`);if(!body.persisted)throw new Error("A mensagem foi enviada, mas não foi salva no atendimento.");setDraft("");await loadMessages(active.id);await load()}catch(e){setNotice(e instanceof Error?e.message:"Não foi possível enviar pelo conector local.")}finally{setBusy(false)}}
 if(loading)return <div className="flex gap-2 p-8"><Loader2 className="animate-spin"/>Carregando...</div>;
 return <div className="page-enter flex h-[calc(100vh-8.7rem)] min-h-[560px] overflow-hidden rounded-2xl border bg-white"><aside className="w-full border-r md:w-[340px]"><div className="flex justify-between border-b p-4"><div><h1 className="font-bold">Atendimentos</h1><p className="text-xs text-slate-500">{rows.length} conversas</p></div><button onClick={()=>void load()} aria-label="Atualizar"><RefreshCw className="size-4"/></button></div>{rows.map(r=><button key={r.id} onClick={()=>setSelected(r.id)} className={`flex w-full gap-3 border-b p-4 text-left ${selected===r.id?"bg-teal-50":""}`}><MessageCircle className="size-4 text-emerald-600"/><span><b className="block text-sm">{r.customers?.name??"Cliente"}</b><small>{r.channel==="whatsapp_web_local"?"WhatsApp Web Local":r.channel}</small></span></button>)}</aside><section className="hidden flex-1 flex-col md:flex">{active?<><header className="border-b p-4"><b>{active.customers?.name}</b><p className="text-xs text-emerald-700">via {active.channel}</p></header><div className="flex-1 space-y-3 overflow-y-auto bg-[#edf3f1] p-6">{messages.map(m=><div key={m.id} className={`max-w-[78%] rounded-2xl p-3 text-sm ${m.direction==="outbound"?"ml-auto bg-teal-600 text-white":"bg-white"}`}>{m.content}</div>)}</div><div className="border-t p-4"><button onClick={()=>void generate()} disabled={busy} className="mb-2 flex gap-2 rounded-lg bg-violet-50 px-3 py-2 text-xs font-semibold text-violet-700"><Bot className="size-4"/>Gerar resposta com IA</button>{notice&&<p className="mb-2 text-xs text-amber-700">{notice}</p>}{sources.length>0&&<p className="mb-2 text-xs text-slate-500">Fontes: {sources.map(source=>[source.fabricante,source.modelo,source.tipo_documento,source.pagina?`Página ${source.pagina}`:null].filter(Boolean).join(" • ")||source.titulo).join("; ")}</p>}<div className="flex gap-2"><textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={2} className="flex-1 rounded-xl border p-3"/><button onClick={()=>void send()} disabled={busy||!draft.trim()} className="rounded-xl bg-teal-600 p-3 text-white"><Send/></button></div><p className="mt-2 text-[10px] text-slate-400">A IA somente gera o rascunho; o envio exige o clique do atendente.</p></div></>:<div className="grid flex-1 place-items-center text-sm text-slate-500">{notice||"Nenhuma conversa."}</div>}</section></div>}
