"use client";

import { useEffect, useRef, useState } from "react";
import { Check, LoaderCircle, Search, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export type CustomerOption = { id:string; name:string; phone:string; whatsapp:string|null; email:string|null; address:string|null };

export function CustomerAutocomplete({ value, onSelect, disabled=false }: { value:CustomerOption|null; onSelect:(customer:CustomerOption|null)=>void; disabled?:boolean }) {
  const [term,setTerm]=useState(value?.name??""); const [results,setResults]=useState<CustomerOption[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [open,setOpen]=useState(false); const requestRef=useRef(0);
  useEffect(()=>{ if(value) setTerm(value.name); },[value]);
  useEffect(()=>{ const query=term.trim(); if(value?.name===query){setResults([]);return;} if(query.length<2){setResults([]);setOpen(false);return;} const timer=setTimeout(async()=>{const request=++requestRef.current;const supabase=createClient();if(!supabase){setError("Supabase não configurado.");return;}setLoading(true);setError("");const safe=query.replace(/[,%()]/g," ");const {data,error}=await supabase.from("customers").select("id,name,phone,whatsapp,email,address").or(`name.ilike.%${safe}%,phone.ilike.%${safe}%,whatsapp.ilike.%${safe}%,email.ilike.%${safe}%`).order("name").limit(8);if(request!==requestRef.current)return;if(error){setError(`[${error.code}] ${error.message}`);setResults([]);}else{setResults(data??[]);setOpen(true);}setLoading(false);},350);return()=>clearTimeout(timer);},[term,value]);
  function clear(){onSelect(null);setTerm("");setResults([]);setOpen(false);}
  return <div className="relative"><label className="text-xs font-semibold text-slate-600">Cliente *</label><div className="relative mt-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input disabled={disabled} value={term} onFocus={()=>results.length&&setOpen(true)} onChange={(e)=>{setTerm(e.target.value);if(value)onSelect(null)}} placeholder="Digite nome, telefone, WhatsApp ou e-mail" className="h-10 w-full rounded-xl border border-slate-200 pl-9 pr-10 text-sm outline-none focus:border-teal-500"/>{loading?<LoaderCircle className="absolute right-3 top-1/2 size-4 -translate-y-1/2 animate-spin text-teal-600"/>:(term&&<button type="button" onClick={clear} aria-label="Limpar cliente" className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400"><X className="size-4"/></button>)}</div>{value&&<div className="mt-2 flex items-center gap-2 rounded-lg bg-teal-50 px-3 py-2 text-xs text-teal-800"><Check className="size-4"/><span><b>{value.name}</b> • {value.phone}{value.email?` • ${value.email}`:""}</span></div>}{error&&<p className="mt-1 text-xs text-rose-600">{error}</p>}{open&&!value&&<div className="absolute z-30 mt-1 max-h-64 w-full overflow-y-auto rounded-xl border border-slate-200 bg-white p-1 shadow-xl">{results.length?results.map((customer)=><button type="button" key={customer.id} onClick={()=>{onSelect(customer);setTerm(customer.name);setOpen(false)}} className="block w-full rounded-lg px-3 py-2 text-left hover:bg-teal-50"><b className="block text-sm text-slate-800">{customer.name}</b><span className="block text-xs text-slate-500">{customer.phone}{customer.email?` • ${customer.email}`:""}</span></button>):<p className="p-3 text-sm text-slate-500">Nenhum cliente encontrado.</p>}</div>}</div>;
}
