"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, Boxes, CircleDollarSign, ClipboardList, Computer, Headphones, LoaderCircle, MessageCircle, PackageCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type RecentOrder={id:string;number:string;status:string;total_value:number;customers:{name:string}|null;equipment:{type:string;manufacturer:string|null;model:string|null}|null};
const statusLabels:Record<string,string>={received:"Recebido",analysis:"Em análise",waiting_quote:"Aguardando orçamento",quote_sent:"Orçamento enviado",quote_approved:"Orçamento aprovado",maintenance:"Em manutenção",waiting_part:"Aguardando peça",ready:"Pronto",delivered:"Entregue",cancelled:"Cancelado"};

export function DashboardOverview({userName}:{userName:string}){
 const [salesToday,setSalesToday]=useState({count:0,revenue:0,profit:0,products:0});
 const [serviceStock,setServiceStock]=useState({reserved:0,used:0,waiting:0});
 const [counts,setCounts]=useState({open:0,waiting:0,inProgress:0,maintenance:0,quotes:0,finished:0,lowStock:0,outOfStock:0});const [orders,setOrders]=useState<RecentOrder[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{void(async()=>{const s=createClient();if(!s)return;const results=await Promise.all([s.from("conversations").select("id",{count:"exact",head:true}).neq("status","closed"),s.from("conversations").select("id",{count:"exact",head:true}).eq("status","waiting"),s.from("conversations").select("id",{count:"exact",head:true}).eq("status","in_progress"),s.from("service_orders").select("id",{count:"exact",head:true}).eq("status","maintenance"),s.from("quotes").select("id",{count:"exact",head:true}).eq("status","pending"),s.from("service_orders").select("id",{count:"exact",head:true}).in("status",["ready","delivered"]),s.from("service_orders").select("id,number,status,total_value,customers(name),equipment(type,manufacturer,model)").order("created_at",{ascending:false}).limit(5),s.from("products").select("id,current_stock,minimum_stock").eq("active",true)]);const [open,waiting,inProgress,maintenance,quotes,finished,recent,inventory]=results;const critical=inventory.data??[];const existingError=results.slice(0,7).find(r=>r.error)?.error;if(existingError)setError(`[${existingError.code}] ${existingError.message}`);else{setCounts({open:open.count??0,waiting:waiting.count??0,inProgress:inProgress.count??0,maintenance:maintenance.count??0,quotes:quotes.count??0,finished:finished.count??0,lowStock:critical.filter(p=>Number(p.current_stock)>0&&Number(p.current_stock)<=Number(p.minimum_stock)).length,outOfStock:critical.filter(p=>Number(p.current_stock)<=0).length});setOrders((recent.data??[]) as unknown as RecentOrder[])}const day=new Date();day.setHours(0,0,0,0);const [sales,osItems,waitingParts]=await Promise.all([s.from("sales").select("id,total,gross_profit,sale_items(quantity,item_type)").eq("status","completed").gte("created_at",day.toISOString()),s.from("service_order_items").select("quantity,stock_status").eq("item_type","product").in("stock_status",["RESERVED","USED"]),s.from("service_orders").select("id",{count:"exact",head:true}).eq("status","waiting_part")]);if(!sales.error){const rows=sales.data??[];setSalesToday({count:rows.length,revenue:rows.reduce((a,v)=>a+Number(v.total),0),profit:rows.reduce((a,v)=>a+Number(v.gross_profit),0),products:rows.reduce((a,v)=>a+(v.sale_items??[]).filter(i=>i.item_type==="product").reduce((n,i)=>n+Number(i.quantity),0),0)})}if(!osItems.error)setServiceStock({reserved:(osItems.data??[]).filter(i=>i.stock_status==="RESERVED").reduce((n,i)=>n+Number(i.quantity),0),used:(osItems.data??[]).filter(i=>i.stock_status==="USED").reduce((n,i)=>n+Number(i.quantity),0),waiting:waitingParts.count??0});setLoading(false)})()},[]);
 if(loading)return <div className="flex justify-center gap-2 p-12 text-slate-500"><LoaderCircle className="animate-spin"/>Carregando indicadores...</div>;
 const cards=[["Conversas abertas",counts.open,MessageCircle],["Aguardando resposta",counts.waiting,Headphones],["Em atendimento",counts.inProgress,Headphones],["Em manutenção",counts.maintenance,Computer],["Orçamentos pendentes",counts.quotes,CircleDollarSign],["Serviços finalizados",counts.finished,PackageCheck],["Estoque baixo",counts.lowStock,AlertTriangle],["Produtos sem estoque",counts.outOfStock,Boxes]] as const;
 const saleCards=[["Vendas hoje",salesToday.count],["Faturamento hoje",new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(salesToday.revenue)],["Lucro bruto estimado hoje",new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(salesToday.profit)],["Produtos vendidos hoje",salesToday.products]];
 const serviceCards=[["Peças reservadas",serviceStock.reserved],["Peças usadas em OS",serviceStock.used],["OS aguardando peça",serviceStock.waiting]];
 return <div className="page-enter space-y-6"><div><p className="text-sm text-slate-500">Visão geral com dados do Supabase</p><h1 className="mt-1 text-2xl font-bold">Olá, {userName.split(" ")[0]}</h1></div>{error&&<div className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{error}</div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{saleCards.map(([label,value])=><div key={label} className="rounded-2xl bg-[var(--ciass-navy)] p-5 text-white"><p className="text-sm text-blue-100/70">{label}</p><b className="mt-2 block text-2xl">{value}</b></div>)}</div><div className="grid gap-4 sm:grid-cols-3">{serviceCards.map(([label,value])=><div key={label} className="rounded-2xl border border-orange-200 bg-orange-50 p-5"><p className="text-sm text-slate-600">{label}</p><b className="mt-2 block text-2xl text-[var(--ciass-navy)]">{value}</b></div>)}</div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{label}</p><b className="mt-2 block text-3xl">{value}</b></div><span className="h-fit rounded-xl bg-blue-50 p-3 text-[var(--ciass-navy)]"><Icon className="size-5"/></span></div></div>)}</div><div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Ordens de Serviço recentes</h2></div>{orders.length===0?<div className="grid place-items-center p-10 text-sm text-slate-500"><ClipboardList className="mb-2 size-8"/>Nenhuma OS cadastrada.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Número","Cliente","Equipamento","Status","Total"].map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-t"><td className="px-5 py-4 font-bold text-[var(--ciass-navy)]">{o.number}</td><td className="px-5 py-4">{o.customers?.name??"—"}</td><td className="px-5 py-4">{[o.equipment?.manufacturer,o.equipment?.model].filter(Boolean).join(" ")||o.equipment?.type||"—"}</td><td className="px-5 py-4">{statusLabels[o.status]??o.status}</td><td className="px-5 py-4 font-semibold">{new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(o.total_value)}</td></tr>)}</tbody></table></div>}</div></div>
}
