"use client";

import { useEffect, useState } from "react";
import { CircleDollarSign, ClipboardList, Computer, Headphones, LoaderCircle, MessageCircle, PackageCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type RecentOrder={id:string;number:string;status:string;total_value:number;customers:{name:string}|null;equipment:{type:string;manufacturer:string|null;model:string|null}|null};
const statusLabels:Record<string,string>={received:"Recebido",analysis:"Em análise",waiting_quote:"Aguardando orçamento",quote_sent:"Orçamento enviado",quote_approved:"Orçamento aprovado",maintenance:"Em manutenção",waiting_part:"Aguardando peça",ready:"Pronto",delivered:"Entregue",cancelled:"Cancelado"};

export function DashboardOverview({userName}:{userName:string}){
 const [counts,setCounts]=useState({open:0,waiting:0,inProgress:0,maintenance:0,quotes:0,finished:0});const [orders,setOrders]=useState<RecentOrder[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{void(async()=>{const s=createClient();if(!s)return;const results=await Promise.all([s.from("conversations").select("id",{count:"exact",head:true}).neq("status","closed"),s.from("conversations").select("id",{count:"exact",head:true}).eq("status","waiting"),s.from("conversations").select("id",{count:"exact",head:true}).eq("status","in_progress"),s.from("service_orders").select("id",{count:"exact",head:true}).eq("status","maintenance"),s.from("quotes").select("id",{count:"exact",head:true}).eq("status","pending"),s.from("service_orders").select("id",{count:"exact",head:true}).in("status",["ready","delivered"]),s.from("service_orders").select("id,number,status,total_value,customers(name),equipment(type,manufacturer,model)").order("created_at",{ascending:false}).limit(5)]);const [open,waiting,inProgress,maintenance,quotes,finished,recent]=results;const firstError=results.find(r=>r.error)?.error;if(firstError)setError(`[${firstError.code}] ${firstError.message}`);else{setCounts({open:open.count??0,waiting:waiting.count??0,inProgress:inProgress.count??0,maintenance:maintenance.count??0,quotes:quotes.count??0,finished:finished.count??0});setOrders((recent.data??[]) as unknown as RecentOrder[])}setLoading(false)})()},[]);
 if(loading)return <div className="flex justify-center gap-2 p-12 text-slate-500"><LoaderCircle className="animate-spin"/>Carregando indicadores...</div>;
 const cards=[["Conversas abertas",counts.open,MessageCircle],["Aguardando resposta",counts.waiting,Headphones],["Em atendimento",counts.inProgress,Headphones],["Em manutenção",counts.maintenance,Computer],["Orçamentos pendentes",counts.quotes,CircleDollarSign],["Serviços finalizados",counts.finished,PackageCheck]] as const;
 return <div className="page-enter space-y-6"><div><p className="text-sm text-slate-500">Visão geral com dados do Supabase</p><h1 className="mt-1 text-2xl font-bold">Olá, {userName.split(" ")[0]}</h1></div>{error&&<div className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{error}</div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label,value,Icon])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{label}</p><b className="mt-2 block text-3xl">{value}</b></div><span className="h-fit rounded-xl bg-teal-50 p-3 text-teal-700"><Icon className="size-5"/></span></div></div>)}</div><div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Ordens de Serviço recentes</h2></div>{orders.length===0?<div className="grid place-items-center p-10 text-sm text-slate-500"><ClipboardList className="mb-2 size-8"/>Nenhuma OS cadastrada.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Número","Cliente","Equipamento","Status","Total"].map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-t"><td className="px-5 py-4 font-bold text-teal-700">{o.number}</td><td className="px-5 py-4">{o.customers?.name??"—"}</td><td className="px-5 py-4">{[o.equipment?.manufacturer,o.equipment?.model].filter(Boolean).join(" ")||o.equipment?.type||"—"}</td><td className="px-5 py-4">{statusLabels[o.status]??o.status}</td><td className="px-5 py-4 font-semibold">{new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(o.total_value)}</td></tr>)}</tbody></table></div>}</div></div>
}
