"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {CheckCircle2,ClipboardList,LoaderCircle,Pencil,Plus,Search,Trash2,X} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import {CustomerAutocomplete,type CustomerOption} from "@/components/customer-autocomplete";
import {ServiceOrderItems} from "@/components/service-order-items";
type Status="received"|"analysis"|"waiting_quote"|"quote_sent"|"quote_approved"|"maintenance"|"waiting_part"|"ready"|"delivered"|"cancelled";
type Equipment={id:string;type:string;manufacturer:string|null;model:string|null;serial_number:string|null};type Technician={id:string;full_name:string};
type Order={id:string;number:string;customer_id:string;equipment_id:string;entry_date:string;reported_issue:string;technical_diagnosis:string|null;service_performed:string|null;parts_value:number;labor_value:number;total_value:number;technician_id:string|null;expected_delivery:string|null;status:Status;notes:string|null;customers:CustomerOption|null;equipment:Equipment|null};
type Form={customer:CustomerOption|null;equipment_id:string;reported_issue:string;technical_diagnosis:string;service_performed:string;technician_id:string;expected_delivery:string;status:Status;notes:string};
const empty:Form={customer:null,equipment_id:"",reported_issue:"",technical_diagnosis:"",service_performed:"",technician_id:"",expected_delivery:"",status:"received",notes:""};
const labels:Record<Status,string>={received:"Recebido",analysis:"Em análise",waiting_quote:"Aguardando orçamento",quote_sent:"Orçamento enviado",quote_approved:"Orçamento aprovado",maintenance:"Em manutenção",waiting_part:"Aguardando peça",ready:"Pronto",delivered:"Entregue",cancelled:"Cancelado"};
const types:Record<string,string>={computer:"Computador",notebook:"Notebook",printer:"Impressora",monitor:"Monitor",router:"Roteador",other:"Outro"};
const selection="id,number,customer_id,equipment_id,entry_date,reported_issue,technical_diagnosis,service_performed,parts_value,labor_value,total_value,technician_id,expected_delivery,status,notes,customers(id,name,phone,whatsapp,email,address),equipment(id,type,manufacturer,model,serial_number)";
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v);const errorText=(e:{message:string;code?:string})=>[e.code?`[${e.code}]`:"",e.message].filter(Boolean).join(" — ");
export function ServiceOrderManagement(){
 const [orders,setOrders]=useState<Order[]>([]),[equipment,setEquipment]=useState<Equipment[]>([]),[technicians,setTechnicians]=useState<Technician[]>([]);const [form,setForm]=useState<Form>(empty),[editing,setEditing]=useState<Order|null>(null);const [open,setOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[equipmentLoading,setEquipmentLoading]=useState(false);const [query,setQuery]=useState(""),[statusFilter,setStatusFilter]=useState(""),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const load=useCallback(async()=>{const s=createClient();if(!s)return;setLoading(true);const [a,b]=await Promise.all([s.from("service_orders").select(selection).order("created_at",{ascending:false}),s.from("profiles").select("id,full_name").eq("active",true).order("full_name")]);if(a.error)setError(errorText(a.error));else setOrders((a.data??[]) as unknown as Order[]);setTechnicians(b.data??[]);setLoading(false)},[]);useEffect(()=>{void load()},[load]);
 async function loadEquipment(customerId:string,selected=""){const s=createClient();if(!s)return;setEquipmentLoading(true);const r=await s.from("equipment").select("id,type,manufacturer,model,serial_number").eq("customer_id",customerId).order("created_at",{ascending:false});if(r.error)setError(errorText(r.error));else{setEquipment(r.data??[]);if(selected&&!r.data?.some(i=>i.id===selected))setForm(v=>({...v,equipment_id:""}))}setEquipmentLoading(false)}
 function chooseCustomer(customer:CustomerOption|null){setForm(v=>({...v,customer,equipment_id:""}));setEquipment([]);if(customer)void loadEquipment(customer.id)}function create(){setEditing(null);setForm(empty);setEquipment([]);setError("");setOpen(true)}
 function edit(o:Order){setEditing(o);setForm({customer:o.customers,equipment_id:o.equipment_id,reported_issue:o.reported_issue,technical_diagnosis:o.technical_diagnosis??"",service_performed:o.service_performed??"",technician_id:o.technician_id??"",expected_delivery:o.expected_delivery??"",status:o.status,notes:o.notes??""});setError("");setOpen(true);void loadEquipment(o.customer_id,o.equipment_id)}
 async function save(e:FormEvent){e.preventDefault();const s=createClient();if(!s||!form.customer||!form.equipment_id||!form.reported_issue.trim()){setError("Selecione cliente e equipamento e informe o defeito.");return}setSaving(true);const payload={customer_id:form.customer.id,equipment_id:form.equipment_id,reported_issue:form.reported_issue.trim(),technical_diagnosis:form.technical_diagnosis.trim()||null,service_performed:form.service_performed.trim()||null,technician_id:form.technician_id||null,expected_delivery:form.expected_delivery||null,status:form.status,notes:form.notes.trim()||null};const r=editing?await s.from("service_orders").update(payload).eq("id",editing.id).select(selection).single():await s.from("service_orders").insert(payload).select(selection).single();setSaving(false);if(r.error){setError(errorText(r.error));return}setSuccess(editing?"Ordem de Serviço atualizada.":`Ordem de Serviço ${(r.data as {number:string}).number} criada.`);setOpen(false);await load()}
 async function remove(o:Order){if(!confirm(`Excluir ${o.number}?`))return;const s=createClient();if(!s)return;const r=await s.from("service_orders").delete().eq("id",o.id);if(r.error)setError(errorText(r.error));else await load()}
 const visible=useMemo(()=>{const q=query.toLowerCase();return orders.filter(o=>(!statusFilter||o.status===statusFilter)&&(!q||[o.number,o.customers?.name,o.reported_issue].some(v=>v?.toLowerCase().includes(q))))},[orders,query,statusFilter]);
 return <div className="page-enter space-y-5"><header className="flex justify-between"><div><h1 className="text-2xl font-bold">Ordens de Serviço</h1><p className="text-sm text-slate-500">Controle do serviço, produtos, reservas e custos</p></div><button onClick={create} className="btn"><Plus className="size-4"/>Nova OS</button></header>{success&&<Notice text={success} close={()=>setSuccess("")}/>} {error&&!open&&<ErrorBox text={error}/>}<div className="flex gap-3"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar número, cliente ou defeito" className="input mt-0 pl-9"/></label><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="input mt-0 max-w-56"><option value="">Todos os status</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="rounded-2xl border bg-white">{loading?<Load/>:visible.length===0?<div className="grid place-items-center p-12 text-slate-500"><ClipboardList className="mb-2 size-8"/>Nenhuma OS cadastrada.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr>{["Número","Cliente","Equipamento","Entrada","Status","Total","Ações"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(o=><tr key={o.id}><td className="font-bold text-teal-700">{o.number}</td><td>{o.customers?.name}</td><td>{equipmentName(o.equipment)}</td><td>{new Date(`${o.entry_date}T12:00:00`).toLocaleDateString("pt-BR")}</td><td>{labels[o.status]}</td><td className="font-semibold">{money(o.total_value)}</td><td><div className="flex gap-3"><button title="Editar e gerenciar itens" onClick={()=>edit(o)}><Pencil className="size-4 text-teal-700"/></button><button title="Excluir" onClick={()=>void remove(o)}><Trash2 className="size-4 text-rose-600"/></button></div></td></tr>)}</tbody></table></div>}</div>{open&&<OrderModal editing={editing} form={form} setForm={setForm} equipment={equipment} technicians={technicians} equipmentLoading={equipmentLoading} saving={saving} error={error} close={()=>setOpen(false)} save={save} chooseCustomer={chooseCustomer}/>}</div>
}
function OrderModal(p:{editing:Order|null;form:Form;setForm:React.Dispatch<React.SetStateAction<Form>>;equipment:Equipment[];technicians:Technician[];equipmentLoading:boolean;saving:boolean;error:string;close:()=>void;save:(e:FormEvent)=>void;chooseCustomer:(c:CustomerOption|null)=>void}){return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-4"><div className="mx-auto my-4 max-w-5xl rounded-2xl bg-white"><header className="flex justify-between border-b p-5"><b>{p.editing?`${p.editing.number} — dados e itens`:"Nova Ordem de Serviço"}</b><button onClick={p.close}><X/></button></header><form onSubmit={p.save} className="p-5"><CustomerAutocomplete value={p.form.customer} onSelect={p.chooseCustomer} disabled={p.saving}/><label className="field mt-4 block">Equipamento *<select disabled={!p.form.customer||p.equipmentLoading} value={p.form.equipment_id} onChange={e=>p.setForm(v=>({...v,equipment_id:e.target.value}))} className="input"><option value="">Selecione</option>{p.equipment.map(i=><option key={i.id} value={i.id}>{equipmentName(i)}</option>)}</select></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><Area label="Defeito informado *" value={p.form.reported_issue} set={v=>p.setForm(f=>({...f,reported_issue:v}))}/><Area label="Diagnóstico técnico" value={p.form.technical_diagnosis} set={v=>p.setForm(f=>({...f,technical_diagnosis:v}))}/><Area label="Serviço realizado" value={p.form.service_performed} set={v=>p.setForm(f=>({...f,service_performed:v}))}/><label className="field">Técnico<select value={p.form.technician_id} onChange={e=>p.setForm(f=>({...f,technician_id:e.target.value}))} className="input"><option value="">Não definido</option>{p.technicians.map(t=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select></label><Field label="Previsão de entrega" type="date" value={p.form.expected_delivery} set={v=>p.setForm(f=>({...f,expected_delivery:v}))}/><label className="field">Status<select value={p.form.status} onChange={e=>p.setForm(f=>({...f,status:e.target.value as Status}))} className="input">{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><Area label="Observações" value={p.form.notes} set={v=>p.setForm(f=>({...f,notes:v}))}/></div>{p.editing&&<ServiceOrderItems serviceOrderId={p.editing.id}/>} {p.error&&<ErrorBox text={p.error}/>}<footer className="mt-5 flex justify-end gap-2"><button type="button" onClick={p.close} className="btn-secondary">Fechar</button><button disabled={p.saving} className="btn">{p.saving&&<LoaderCircle className="animate-spin"/>}Salvar OS</button></footer></form></div></div>}
function equipmentName(i:Equipment|null){return i?[types[i.type]??i.type,i.manufacturer,i.model,i.serial_number?`S/N ${i.serial_number}`:null].filter(Boolean).join(" • "):"—"}function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="field">{label}<input type={type} value={value} onChange={e=>set(e.target.value)} className="input"/></label>}function Area({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="field">{label}<textarea value={value} onChange={e=>set(e.target.value)} className="textarea"/></label>}function ErrorBox({text}:{text:string}){return <div role="alert" className="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{text}</div>}function Notice({text,close}:{text:string;close:()=>void}){return <div className="flex gap-2 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 className="size-5"/>{text}<button onClick={close} className="ml-auto"><X className="size-4"/></button></div>}function Load(){return <div className="flex justify-center gap-2 p-12"><LoaderCircle className="animate-spin"/>Carregando...</div>}
