"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowDownUp, Building2, Copy, LoaderCircle, PackagePlus, Pencil, Plus, Search, Tags, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export type StoreView="Produtos"|"Categorias"|"Estoque"|"Movimentações"|"Fornecedores";
type Category={id:string;name:string;description:string|null;active:boolean};
type Supplier={id:string;name:string;legal_name:string|null;cnpj:string|null;phone:string|null;whatsapp:string|null;email:string|null;contact_name:string|null;address:string|null;notes:string|null;active:boolean};
type Product={id:string;internal_code:string;barcode:string|null;name:string;description:string|null;category_id:string|null;brand:string|null;model:string|null;unit:string;primary_supplier_id:string|null;purchase_price:number;sale_price:number;average_cost:number;current_stock:number;minimum_stock:number;stock_location:string|null;active:boolean;product_categories:{name:string}|null};
type Movement={id:string;movement_type:string;quantity:number;previous_stock:number;resulting_stock:number;unit_cost:number;origin:string;notes:string|null;created_at:string;products:{name:string;internal_code:string}|null;profiles:{full_name:string}|null;suppliers:{name:string}|null};

const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const initialCategories=["Computadores","Notebooks","Impressoras","Monitores","Roteadores","Redes","Periféricos","Teclados","Mouses","Headsets","Cabos","Adaptadores","Fontes","Memórias","SSD","HD","Gabinetes","Placas-mãe","Placas de vídeo","Processadores","Coolers","Baterias","Carregadores","Tintas","Toners","Peças para impressoras","Ferramentas","Acessórios","Outros"];

export function StoreInventoryManagement({view,canManage}:{view:StoreView;canManage:boolean}){
 const supabase=useMemo(()=>createClient(),[]); const [categories,setCategories]=useState<Category[]>([]); const [suppliers,setSuppliers]=useState<Supplier[]>([]); const [products,setProducts]=useState<Product[]>([]); const [movements,setMovements]=useState<Movement[]>([]); const [query,setQuery]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [modal,setModal]=useState<"category"|"supplier"|"product"|"entry"|"adjust"|null>(null); const [selected,setSelected]=useState<Product|null>(null); const [page,setPage]=useState(0); const pageSize=20;
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);setError("");const [c,s,p,m]=await Promise.all([supabase.from("product_categories").select("*").order("name"),supabase.from("suppliers").select("*").order("name"),supabase.from("products").select("*,product_categories(name)").order("name").range(page*pageSize,page*pageSize+pageSize-1),supabase.from("stock_movements").select("*,products(name,internal_code),profiles(full_name),suppliers(name)").order("created_at",{ascending:false}).limit(100)]);const issue=[c,s,p,m].find(result=>result.error)?.error;if(issue)setError(`[${issue.code}] ${issue.message}. Execute supabase/store_inventory.sql após revisar o backup.`);else{setCategories((c.data??[]) as Category[]);setSuppliers((s.data??[]) as Supplier[]);setProducts((p.data??[]) as unknown as Product[]);setMovements((m.data??[]) as unknown as Movement[])}setLoading(false)},[supabase,page]);
 useEffect(()=>{void load()},[load]);
 const filtered=products.filter(p=>[p.name,p.internal_code,p.barcode,p.brand,p.model].some(x=>x?.toLowerCase().includes(query.toLowerCase())));
 if(loading)return <div className="grid place-items-center py-20 text-slate-500"><LoaderCircle className="mb-3 animate-spin"/>Carregando {view.toLowerCase()}...</div>;
 const titles:Record<StoreView,[string,string]>={Produtos:["Produtos","Catálogo, preços e disponibilidade"],Categorias:["Categorias","Organize o catálogo sem enumerações fixas"],Fornecedores:["Fornecedores","Parceiros e contatos comerciais"],Estoque:["Estoque","Entradas, ajustes e alertas de reposição"],Movimentações:["Movimentações","Histórico imutável de entradas e saídas"]};
 return <div className="page-enter space-y-5"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-[var(--ciass-orange)]">LOJA</p><h1 className="text-2xl font-bold text-slate-950">{titles[view][0]}</h1><p className="text-sm text-slate-500">{titles[view][1]}</p></div>{canManage&&<div className="flex gap-2">{view==="Produtos"&&<button className="btn" onClick={()=>{setSelected(null);setModal("product")}}><Plus className="size-4"/>Novo Produto</button>}{view==="Categorias"&&<button className="btn" onClick={()=>setModal("category")}><Tags className="size-4"/>Nova Categoria</button>}{view==="Fornecedores"&&<button className="btn" onClick={()=>setModal("supplier")}><Building2 className="size-4"/>Novo Fornecedor</button>}{view==="Estoque"&&<><button className="btn" onClick={()=>setModal("entry")}><PackagePlus className="size-4"/>Entrada</button><button className="btn-secondary" onClick={()=>setModal("adjust")}><ArrowDownUp className="size-4"/>Ajuste</button></>}</div>}</header>{error&&<div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{error}</div>}
 {(view==="Produtos"||view==="Estoque")&&<><div className="ciass-card flex flex-col gap-3 p-4 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="input !mt-0 pl-9" placeholder="Nome, código interno ou código de barras"/></label><span className="rounded-xl bg-slate-100 px-4 py-2 text-sm text-slate-600">{filtered.length} registros nesta página</span></div><ProductTable products={filtered} stockOnly={view==="Estoque"} canManage={canManage} onEdit={p=>{setSelected(p);setModal("product")}} onDuplicate={p=>{setSelected({...p,id:"",internal_code:`${p.internal_code}-COPIA`,barcode:null,name:`${p.name} (cópia)`});setModal("product")}}/><div className="flex justify-end gap-2"><button disabled={page===0} className="btn-secondary" onClick={()=>setPage(Math.max(0,page-1))}>Anterior</button><button disabled={products.length<pageSize} className="btn-secondary" onClick={()=>setPage(page+1)}>Próxima</button></div></>}
 {view==="Categorias"&&<CategoryTable rows={categories} canManage={canManage} onToggle={async row=>{await supabase?.from("product_categories").update({active:!row.active}).eq("id",row.id);void load()}}/>}
 {view==="Fornecedores"&&<SupplierTable rows={suppliers} canManage={canManage}/>}
 {view==="Movimentações"&&<MovementTable rows={movements}/>}
 {modal&&<Modal title={{category:"Nova categoria",supplier:"Novo fornecedor",product:selected?.id?"Editar produto":"Novo produto",entry:"Entrada de mercadoria",adjust:"Ajuste de estoque"}[modal]} onClose={()=>setModal(null)}>{modal==="category"&&<CategoryForm onDone={()=>{setModal(null);void load()}}/>}{modal==="supplier"&&<SupplierForm onDone={()=>{setModal(null);void load()}}/>}{modal==="product"&&<ProductForm product={selected} categories={categories} suppliers={suppliers} onDone={()=>{setModal(null);void load()}}/>}{modal==="entry"&&<EntryForm products={products} suppliers={suppliers} onDone={()=>{setModal(null);void load()}}/>}{modal==="adjust"&&<AdjustForm products={products} onDone={()=>{setModal(null);void load()}}/>}</Modal>}</div>;
}

function ProductTable({products,stockOnly,canManage,onEdit,onDuplicate}:{products:Product[];stockOnly:boolean;canManage:boolean;onEdit:(p:Product)=>void;onDuplicate:(p:Product)=>void}){return <div className="ciass-card overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead><tr>{(stockOnly?["Código","Produto","Categoria","Estoque","Mínimo","Custo médio","Valor potencial","Status"]:["Código","Produto","Categoria","Estoque","Compra","Venda","Margem","Status","Ações"]).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{products.map(p=>{const margin=p.sale_price>0?((p.sale_price-p.average_cost)/p.sale_price)*100:0;const tone=!p.active?"inactive":p.current_stock<=0?"empty":p.current_stock<=p.minimum_stock?"low":"ok";return <tr key={p.id}><td className="font-semibold text-[var(--ciass-navy)]">{p.internal_code}</td><td><b>{p.name}</b><small className="block text-slate-500">{[p.brand,p.model].filter(Boolean).join(" ")}</small></td><td>{p.product_categories?.name??"—"}</td><td>{p.current_stock} {p.unit}</td>{stockOnly?<><td>{p.minimum_stock}</td><td>{money.format(p.average_cost)}</td><td>{money.format(p.current_stock*p.sale_price)}</td></>:<><td>{money.format(p.purchase_price)}</td><td>{money.format(p.sale_price)}</td><td>{margin.toFixed(1)}%</td></>}<td><StockBadge tone={tone}/></td>{!stockOnly&&<td>{canManage&&<div className="flex gap-2"><button aria-label="Editar produto" onClick={()=>onEdit(p)}><Pencil className="size-4"/></button><button aria-label="Duplicar produto" onClick={()=>onDuplicate(p)}><Copy className="size-4"/></button></div>}</td>}</tr>})}</tbody></table></div>}
function StockBadge({tone}:{tone:"inactive"|"empty"|"low"|"ok"}){const map={inactive:["Inativo","bg-slate-100 text-slate-600"],empty:["Sem estoque","bg-rose-100 text-rose-700"],low:["Estoque baixo","bg-orange-100 text-orange-800"],ok:["Normal","bg-emerald-100 text-emerald-700"]};return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${map[tone][1]}`}>{map[tone][0]}</span>}
function CategoryTable({rows,canManage,onToggle}:{rows:Category[];canManage:boolean;onToggle:(r:Category)=>void}){return <div className="ciass-card grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-3">{rows.map(r=><div key={r.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-4"><span className="rounded-xl bg-blue-50 p-2 text-[var(--ciass-navy)]"><Tags/></span><div className="flex-1"><b>{r.name}</b><p className="text-xs text-slate-500">{r.description||"Categoria de produtos"}</p></div>{canManage&&<button onClick={()=>onToggle(r)} className="text-xs font-semibold text-[var(--ciass-orange)]">{r.active?"Desativar":"Ativar"}</button>}</div>)}</div>}
function SupplierTable({rows,canManage}:{rows:Supplier[];canManage:boolean}){return <div className="ciass-card overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr>{["Fornecedor","Contato","Telefone/WhatsApp","CNPJ","Status"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.name}</b><small className="block text-slate-500">{r.legal_name}</small></td><td>{r.contact_name||r.email||"—"}</td><td>{r.whatsapp||r.phone||"—"}</td><td>{r.cnpj||"—"}</td><td><StockBadge tone={r.active?"ok":"inactive"}/>{canManage&&null}</td></tr>)}</tbody></table></div>}
function MovementTable({rows}:{rows:Movement[]}){return <div className="ciass-card overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead><tr>{["Data","Produto","Tipo","Quantidade","Anterior","Posterior","Origem","Usuário","Fornecedor"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString("pt-BR")}</td><td><b>{r.products?.name}</b><small className="block">{r.products?.internal_code}</small></td><td>{r.movement_type}</td><td className={r.quantity<0?"text-rose-600":"text-emerald-700"}>{r.quantity}</td><td>{r.previous_stock}</td><td>{r.resulting_stock}</td><td>{r.origin}</td><td>{r.profiles?.full_name??"—"}</td><td>{r.suppliers?.name??"—"}</td></tr>)}</tbody></table></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><header className="sticky top-0 flex items-center justify-between border-b bg-white p-5"><h2 className="text-lg font-bold">{title}</h2><button onClick={onClose}><X/></button></header><div className="p-5">{children}</div></div></div>}
function Submit({children="Salvar"}:{children?:string}){return <button className="btn mt-5" type="submit">{children}</button>}
function CategoryForm({onDone}:{onDone:()=>void}){async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const s=createClient();const {error}=await s!.from("product_categories").insert({name:f.get("name"),description:f.get("description")||null});if(!error)onDone()}return <form onSubmit={save}><label className="field">Nome<input name="name" required className="input"/></label><label className="field mt-4 block">Descrição<textarea name="description" className="textarea"/></label><Submit/></form>}
function SupplierForm({onDone}:{onDone:()=>void}){async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const s=createClient();const {error}=await s!.from("suppliers").insert({name:f.name,legal_name:f.legal_name||null,cnpj:f.cnpj||null,phone:f.phone||null,whatsapp:f.whatsapp||null,email:f.email||null,contact_name:f.contact_name||null,address:f.address||null,notes:f.notes||null});if(!error)onDone()}return <form onSubmit={save} className="grid gap-4 sm:grid-cols-2">{[["name","Nome"],["legal_name","Razão social"],["cnpj","CNPJ"],["contact_name","Contato"],["phone","Telefone"],["whatsapp","WhatsApp"],["email","E-mail"],["address","Endereço"]].map(([n,l])=><label key={n} className="field">{l}<input name={n} required={n==="name"} className="input"/></label>)}<label className="field sm:col-span-2">Observações<textarea name="notes" className="textarea"/></label><div><Submit/></div></form>}
function ProductForm({product,categories,suppliers,onDone}:{product:Product|null;categories:Category[];suppliers:Supplier[];onDone:()=>void}){async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const payload={internal_code:f.internal_code,name:f.name,barcode:f.barcode||null,description:f.description||null,category_id:f.category_id||null,brand:f.brand||null,model:f.model||null,unit:f.unit,purchase_price:Number(f.purchase_price),sale_price:Number(f.sale_price),minimum_stock:Number(f.minimum_stock),stock_location:f.stock_location||null,primary_supplier_id:f.primary_supplier_id||null};const s=createClient();const result=product?.id?await s!.from("products").update(payload).eq("id",product.id):await s!.from("products").insert(payload);if(!result.error)onDone()}const margin=product&&product.sale_price?((product.sale_price-product.purchase_price)/product.sale_price)*100:0;return <form onSubmit={save} className="space-y-5"><FormSection title="Identificação"><Grid fields={[["internal_code","Código interno",product?.internal_code],["barcode","Código de barras",product?.barcode],["name","Nome",product?.name],["brand","Marca",product?.brand],["model","Modelo",product?.model]]}/><label className="field">Categoria<select name="category_id" defaultValue={product?.category_id??""} className="input"><option value="">Selecione</option>{categories.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></FormSection><FormSection title="Comercial"><Grid fields={[["purchase_price","Preço de compra",product?.purchase_price??0,"number"],["sale_price","Preço de venda",product?.sale_price??0,"number"]]}/><p className="text-sm text-slate-500">Margem estimada atual: <b>{margin.toFixed(1)}%</b>. Markup e margem são indicadores distintos.</p></FormSection><FormSection title="Estoque"><Grid fields={[["unit","Unidade",product?.unit??"UN"],["minimum_stock","Estoque mínimo",product?.minimum_stock??0,"number"],["stock_location","Localização",product?.stock_location]]}/><p className="text-xs text-amber-700"><AlertTriangle className="mr-1 inline size-4"/>O estoque atual não é editável aqui; use Entrada ou Ajuste para registrar histórico.</p></FormSection><FormSection title="Fornecedor"><label className="field">Fornecedor principal<select name="primary_supplier_id" defaultValue={product?.primary_supplier_id??""} className="input"><option value="">Opcional</option>{suppliers.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></FormSection><Submit/></form>}
function FormSection({title,children}:{title:string;children:React.ReactNode}){return <section><h3 className="mb-3 border-b pb-2 text-sm font-bold uppercase tracking-wide text-[var(--ciass-navy)]">{title}</h3><div className="grid gap-4 sm:grid-cols-2">{children}</div></section>}
function Grid({fields}:{fields:(string|number|null|undefined)[][]}){return <>{fields.map(([n,l,v,t])=><label key={String(n)} className="field">{l}<input name={String(n)} defaultValue={v??""} type={String(t||"text")} step={t==="number"?"0.01":undefined} required={["internal_code","name","unit"].includes(String(n))} className="input"/></label>)}</>}
function EntryForm({products,suppliers,onDone}:{products:Product[];suppliers:Supplier[];onDone:()=>void}){async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),s=createClient();const {data:{user}}=await s!.auth.getUser();if(!user)return;const {data:entry,error}=await s!.from("stock_entries").insert({supplier_id:f.get("supplier_id")||null,document_number:f.get("document_number")||null,notes:f.get("notes")||null,created_by:user.id}).select("id").single();if(error||!entry)return;const item=await s!.from("stock_entry_items").insert({entry_id:entry.id,product_id:f.get("product_id"),quantity:Number(f.get("quantity")),unit_purchase_price:Number(f.get("unit_price"))});if(item.error)return;const result=await s!.rpc("confirm_stock_entry",{entry_uuid:entry.id});if(!result.error)onDone()}return <form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><label className="field">Fornecedor<select name="supplier_id" className="input"><option value="">Sem fornecedor</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field">Documento<input name="document_number" className="input"/></label><label className="field sm:col-span-2">Produto<select required name="product_id" className="input"><option value="">Selecione</option>{products.map(x=><option key={x.id} value={x.id}>{x.internal_code} — {x.name}</option>)}</select></label><label className="field">Quantidade<input required min="0.001" step="0.001" type="number" name="quantity" className="input"/></label><label className="field">Compra unitária<input required min="0" step="0.01" type="number" name="unit_price" className="input"/></label><label className="field sm:col-span-2">Observação<textarea name="notes" className="textarea"/></label><div><Submit>Confirmar entrada</Submit></div></form>}
function AdjustForm({products,onDone}:{products:Product[];onDone:()=>void}){async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),s=createClient();const result=await s!.rpc("adjust_product_stock",{product_uuid:f.get("product_id"),delta:Number(f.get("delta")),reason:f.get("reason"),note:f.get("note")||null});if(!result.error)onDone()}return <form onSubmit={save} className="space-y-4"><label className="field">Produto<select required name="product_id" className="input"><option value="">Selecione</option>{products.map(x=><option key={x.id} value={x.id}>{x.internal_code} — {x.name} ({x.current_stock})</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="field">Quantidade (+ entrada / − saída)<input required step="0.001" type="number" name="delta" className="input"/></label><label className="field">Motivo<select required name="reason" className="input">{["AJUSTE","PERDA","AVARIA","DEVOLUCAO_FORNECEDOR","USO_INTERNO","OUTRO"].map(x=><option key={x}>{x}</option>)}</select></label></div><label className="field">Observação obrigatória<textarea required name="note" className="textarea"/></label><Submit>Registrar ajuste</Submit></form>}

export {initialCategories};
